### ISSUE TITLE
How can I hookup Kernel cache for http request?

### ISSUE THREAD

**Issue by Webonaute** [k911/swoole-bundle#119]
I am trying to make work our current project which using FosCacheBundle with swoole. Any hint of how I can hook it to the kernel?

**Comment by Webonaute** [comment]
Hacking HttpKernelRequestHandler seem to do the trick. 
```
        if ($this->kernel instanceof HttpCacheProvider){
            $httpFoundationResponse = $this->kernel->getHttpCache()->handle($httpFoundationRequest);
        }else{
            $httpFoundationResponse = $this->kernel->handle($httpFoundationRequest);
        }

```
Is there a better way to hook this without hacking lib? or is it possible to add support for this?

Thank.

**Comment by k911** [comment]
For know I believe you have to create your own class implementing request handler interface (probably copy) https://github.com/k911/swoole-bundle/blob/develop/src/Bridge/Symfony/HttpKernel/HttpKernelRequestHandler.php

then use symfony to wire it for dependency injection instead of default class

```yaml
services:
  K911\Swoole\Bridge\Symfony\HttpKernel\HttpKernelRequestHandler:
    class: Foo\Bar\YourHttpCacheProviderHttpKernel
```

In the future (when I'll have some time to finish refactor) every part of this bundle will be split to parts that can be decorated/replaced/added on their own.
