### ISSUE TITLE
Slow response time

### ISSUE THREAD

**Issue by Webonaute** [k911/swoole-bundle#120]
**Describe the bug**
I have done some comparaison between running nginx + fpm vs swoole with FostHtppCacheBundle.
on locale with fpm, I have response time never go over 18ms to serve a simple cached json result which is stored in a file on the disk.

On the other hand. for the same call on swoole it take 28ms minimum up to 40ms.

So fpm seem lot twice faster. 

Do you know any tweek I can do to improve swoole response time?

**Environment (please complete the following information):**
 - OS: Mac
 - PHP Version: 7.3.13
 - Symfony Version: 4.4
 - Running in docker: No
 - opcache: enabled

**Comment by k911** [comment]
Could you please provide us more information, especially a swoole bundle configuration?

Also please try bellow configuration options:

```yaml
swoole:
    http_server:
        running_mode: reactor
        hmr: off
        settings:
            reactor_count: auto
            worker_count: auto
```

with symfony production settings (APP_ENV=prod, APP_DEBUG=0)
