### ISSUE TITLE
How do we set Request::HEADER_X_FORWARDED_AWS_ELB in swoole.yaml

### ISSUE THREAD

**Issue by Webonaute** [k911/swoole-bundle#121]
how do I set Request::HEADER_X_FORWARDED_AWS_ELB in swoole.yaml to allow this trusted proxie header? I can't find it in documentation or swoole.yaml reference.

**Comment by k911** [comment]
You can try using:

```yaml
swoole:
  http_server:
     services:
       trust_all_proxies_handler: true
```

If it does not work, you can take a look at
https://github.com/k911/swoole-bundle/blob/develop/src/Bridge/Symfony/HttpFoundation/TrustAllProxiesRequestHandler.php
and either send a Pull Request to add this feature or decorate RequestFactoryInterface via Symfony DI with your own implementation
