### ISSUE TITLE
Daemonize mode seem to crash with AWS codedeploy

### ISSUE THREAD

**Issue by Webonaute** [k911/swoole-bundle#137]
```
root@ip-10-4-84-141:/home/ubuntu# tail -f /opt/codedeploy-agent/deployment-root/aa90b113-d0ec-4151-b986-fb5d639b701a/d-C2NQCNMH2/logs/scripts.log 
2020-02-08 14:50:56 [stdout]  worker_count      4                                          
2020-02-08 14:50:56 [stdout]  reactor_count     2                                          
2020-02-08 14:50:56 [stdout]  memory_limit      3 GiB                                      
2020-02-08 14:50:56 [stdout]  trusted_hosts                                                
2020-02-08 14:50:56 [stdout]  trusted_proxies                                              
2020-02-08 14:50:56 [stdout]  public_dir        /var/www/project/public  
2020-02-08 14:50:56 [stdout] ----------------- ------------------------------------------- 
2020-02-08 14:50:56 [stdout]
2020-02-08 14:50:56 [stderr]+ echo 'Application start end.'
2020-02-08 14:50:56 [stdout]Application start end.
```

Here we have a log that the service `php ${INSTALL_DIR}/bin/console swoole:server:start` started correctly but than the applicationStart event never end and crash like the server is not fully detach from the session.

Here is the config file.
```
swoole:
  http_server:
    port: 50051
    host: 0.0.0.0
    running_mode: reactor
    socket_type: tcp
    ssl_enabled: false
#    trusted_hosts: localhost,127.0.0.1
#    trusted_proxies:
#      - '*'
#      - 127.0.0.1/8
#      - 192.168.2./16

    # enables static file serving
    static: advanced
    # equals to:
    # ---
    # static:
    #     public_dir: '%kernel.project_dir%/public'
    #     strategy: advanced
    # ---
    # strategy can be one of: (default) auto, off, advanced, default
    #   - off: turn off feature
    #   - auto: use 'advanced' when debug enabled or not production environment
    #   - advanced: use request handler class \K911\Swoole\Server\RequestHandler\AdvancedStaticFilesServer
    #   - default: use default swoole static serving (faster than advanced, but supports less content types)

    # enables hot module reload using inotify
    hmr: off
    # hmr can be one of: off, (default) auto, inotify
    #   - off: turn off feature
    #   - auto: use inotify if installed in the system
    #   - inotify: use inotify

    # enables api server on specific port
    # by default it is disabled (can be also enabled using --api flag via cli)
    api: true
    # equals to:
    # ---
    # api:
    #     enabled: true
    #     host: 0.0.0.0
    #     port: 9200

    # additional swoole symfony bundle services
    services:
      # see: \K911\Swoole\Bridge\Symfony\HttpKernel\DebugHttpKernelRequestHandler
      debug_handler: false

      # see: \K911\Swoole\Bridge\Symfony\HttpFoundation\TrustAllProxiesRequestHandler
      trust_all_proxies_handler: true

      # see: \K911\Swoole\Bridge\Symfony\HttpFoundation\CloudFrontRequestFactory
      cloudfront_proto_header_handler: true

      # see: \K911\Swoole\Bridge\Doctrine\ORM\EntityManagerHandler
      entity_manager_handler: true

    # swoole http server settings
    # see https://www.swoole.co.uk/docs/modules/swoole-server/configuration
    settings:
      #reactor_count: 10
      #worker_count: 4
      # when not set, swoole sets these are automatically set based on count of host CPU cores
      #task_worker_count: auto # one of: positive number, "auto", or null to disable creation of task worker processes (default: null)

      log_level: notice
      # can be one of: (default) auto, debug, trace, info, notice, warning, error
      #   - auto: when debug set to debug, when not set to notice
      #   - {debug,trace,info,notice,warning,error}: see swoole configuration

      log_file: '%kernel.logs_dir%/swoole_%kernel.environment%.log'
      pid_file: '/var/run/swoole_http_server_%env(resolve:SERVICE_NAME)%.pid'

      buffer_output_size: 2097152
      # in bytes, 2097152b = 2 MiB

      package_max_length: 8388608
      # in bytes, 8388608b = 8 MiB
```

 Any idea could help me resolve this?
