### ISSUE TITLE
Attempted to call an undefined method named "boot"

### ISSUE THREAD

**Issue by enumag** [k911/swoole-bundle#19]
```
swoole:
    http_server:
        # ...
        services:
            debug_handler: true
            entity_manager_handler: true
```

`debug_handler: true` causes `Attempted to call an undefined method named "boot" of class "K911\Swoole\Bridge\Symfony\HttpKernel\DebugHttpKernelRequestHandler".`

Similarly `entity_manager_handler: true` causes `Attempted to call an undefined method named "boot" of class "K911\Swoole\Bridge\Doctrine\ORM\EntityManagerHandler".`
