### ISSUE TITLE
Errors when setting worker_count and reactor+count through ENV

### ISSUE THREAD

**Issue by Rastusik** [k911/swoole-bundle#243]
**Describe the bug**
Symfony app fails to start with settings such as this:
```yaml
parameters:
    env(WORKER_COUNT): 4
    env(REACTOR_COUNT): 2

swoole:
    http_server:
        settings:
            worker_count: '%env(int:WORKER_COUNT)%'
            reactor_count: '%env(int:REACTOR_COUNT)%'
```

with this error: `The value 0 is too small for path "swoole.http_server.settings.worker_count". Should be greater than or equal to 1`

**Steps To Reproduce**
already mentioned

**Expected behavior**
Symfony app starts normally

The fix is to change the corresponding nodes in Configuration class from integerNode to scalarNode. I'm creating the fix right now.
