### ISSUE TITLE
hot reload not work

### ISSUE THREAD

**Issue by galliroberto** [k911/swoole-bundle#250]
**Describe the bug**

i have installed inotify and enabled it in symfony, but when i change php file, the change is not reflected.
```
static: advanced
hmr: inotify
```

**Environment (please complete the following information):**
 - OS: macOs
 - PHP Version: 7.4.2
 - Swoole Version: latest
 - Symfony Version: 5
 - Running in docker: Yes

**Additional context**
I have set AUTORELOAD_ANY_FILES=1 in docker-compose
```
volumes:
      - ../:/var/www/app
      - ./data/shell_history:/home/utente/shell_history
    networks:
      - network_app
    environment:
      - HISTFILE=/home/utente/shell_history/.zsh_history
      - SWOOLE_TIMEZONE=Europe/Rome
      - DISABLE_DEFAULT_SERVER=1
      - AUTORELOAD_PROGRAMS="swoole"
      - AUTORELOAD_ANY_FILES="yes"
      - PHP_IDE_CONFIG="serverName=application"
      - XDEBUG_CONFIG="idekey=PHPSTORM remote_host=host.docker.internal remote_port=9000"
```
