### ISSUE TITLE
HRM with Docker

### ISSUE THREAD

**Issue by fjogeleit** [k911/swoole-bundle#26]
Hey everybody,

thanks for this nice bundle. It works very well for me. But I have one question about the HRM feature in combination with Docker.

I have a Dockerfile with swoole and inotify:

```
FROM php:7.2-cli-alpine

RUN apk add --no-cache xvfb ttf-freefont fontconfig dbus postgresql-dev autoconf make g++ \
    && docker-php-ext-configure mbstring --enable-mbstring \
    && docker-php-ext-install \
        mbstring \
        pgsql \
        pdo_pgsql \
        bcmath \
    && pecl install swoole inotify redis \
    && docker-php-ext-enable redis \
    && touch /usr/local/etc/php/conf.d/swoole.ini \
    && echo 'extension=swoole.so' > /usr/local/etc/php/conf.d/swoole.ini \
    && touch /usr/local/etc/php/conf.d/inotify.ini \
    && echo 'extension=inotify.so' > /usr/local/etc/php/conf.d/inotify.ini

WORKDIR /var/www

EXPOSE 9501

CMD ["bin/console", "swoole:server:run", "--host=0.0.0.0"]
```
I use this Dockerfile with an docker-compose file which has a php-swoole configuration:

```
  php-swoole:
    build:
      context: './docker/php-swoole'
    depends_on: ['postgres', 'redis']
    volumes:
      - './config:/var/www/config'
      - './src:/var/www/src'
      - './public:/var/www/public'
      - './bin:/var/www/bin'
      - './templates:/var/www/templates'
      - './translations:/var/www/translations'
      - './vendor:/var/www/vendor:cached'
      - './var:/var/www/var'
      - './composer.json:/var/www/composer.json'
      - './docker/php-swoole/php.ini:/usr/local/etc/php/php.ini'
    links: ['postgres:database', 'redis:pubsub']
    env_file: ['./.env.docker']
    ports: ['9501:9501']
```

So all symfony files are linked into the container and all needed extensions for swoole and HRM are installed. The symfony project itself also works fine and as expected. But the HRM doesn't work. I have to restart the container every time I change a file. Did I something wrong? I also tried to change the HRM configuration to `inotify`. The InotifyHRM class is loaded and initialized.

Thanks a lot.

**Comment by k911** [comment]
@fjogeleit Thanks for using it. The other day I was working on running tests within docker container's everything worked fine. You can test it here: https://github.com/k911/swoole-bundle/tree/ci/dockerize

```
docker-compose build --pull
docker-compose run server
```

--

To confirm, you've tried this configuration:

```yaml
swoole:
    http_server:
        // ...
        hmr: 'inotify'
```

along with setting `APP_DEBUG=1` in `.env.docker`?

If the answer is yes, could you create small reproducer repository?
