### ISSUE TITLE
Bundles seems to skip firewalls

### ISSUE THREAD

**Issue by domgraziano** [k911/swoole-bundle#514]
**Describe the bug**
The bundle seems to "skip"the user authentication process in symfony. 
In my security.yaml I have 
```
    firewalls:
        main:
            stateless: true
            anonymous: true
            provider: my_custom_user_provider
            guard:
                authenticators:
                    - App\Security\MyCustomGuard
```
so when I send a request like this  where xxx.xxx.xxx is a valid jwt token, I successfully get a response 
`curl --location --request GET 'http://localhost/someresource/031abb40-a76c-11eb-aacc-0242ac120003' \
--header 'Authorization: Bearer xxx.xxx.xxx' `

but when I send another request just after with, where yyy.yyy.yyy is not a valid token the user should be denied access whereas what I get is the previous response 
`curl --location --request GET 'http://localhost/someresource/031abb40-a76c-11eb-aacc-0242ac120003' \
--header 'Authorization: Bearer yyy.yyy.yyy' `

If I stop and restart the swoole server and resend 
`curl --location --request GET 'http://localhost/someresource/031abb40-a76c-11eb-aacc-0242ac120003' \
--header 'Authorization: Bearer yyy.yyy.yyy' `
I then have an access denied

**Steps To Reproduce**
Try to use a user provider and security with  stateless and anonymous set to true in a symfony app with an authentication mechanism based on Authorization http headers.

**Expected behavior**
When I send a second request with an invalid authorization token I expect that to pass first via the security layer I declare in my symfony app (that is the behaviour I have using the same app with php-fpm).

**Environment (please complete the following information):**
 - OS:  Linux
 - PHP Version: 7.3
 - Swoole Version: 4.6.6
 - Symfony Version: 4.4.16
 - Running in docker: Yes

**Additional context**
Note: I have already seen https://github.com/k911/swoole-bundle/issues/489 and I am following already this example https://github.com/k911/swoole-bundle/blob/develop/tests/Fixtures/Symfony/app/config/session/swoole.yaml

</p>
</details>
